repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]

      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: poetry run bandit -r src
        language: system
        pass_filenames: false